from setuptools import setup, find_packages

with open("README.md", "r") as fh:
    long_description = fh.read()

setup(
    name="Flask API",
    version="1.0.0",
    author="ClearCB",
    author_email="abelcasasccb@gmail.com",
    description="Flask CRUD Mongo Api",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/ClearCB/ollivanders-flask",
    packages=find_packages(),
    include_package_data=True,
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.10",
    install_requires=[
        "aniso8601==9.0.1",
        "attrs==22.2.0",
        "black==23.1.0",
        "cachetools==5.3.0",
        "chardet==5.1.0",
        "colorama==0.4.6",
        "coverage==7.2.2",
        "distlib==0.3.6",
        "dnspython==2.3.0",
        "exceptiongroup==1.1.0",
        "filelock==3.10.0",
        "Flask==2.2.3",
        "Flask-Cors==3.0.10",
        "iniconfig==2.0.0",
        "itsdangerous==2.1.2",
        "Jinja2==3.1.2",
        "MarkupSafe==2.1.2",
        "mypy-extensions==1.0.0",
        "packaging==23.0",
        "pathspec==0.11.1",
        "platformdirs==3.1.1",
        "pluggy==1.0.0",
        "pymongo==4.3.3",
        "pyproject_api==1.5.1",
        "pytest==7.2.2",
        "pytz==2022.7.1",
        "six==1.16.0",
        "tomli==2.0.1",
        "tox==4.4.7",
        "virtualenv==20.21.0",
        "Werkzeug==2.2.3",
        "gitdb==4.0.10",
        "GitPython==3.1.31",
        "bandit==1.7.5",
        "mdurl==0.1.2",
        "markdown-it-py==2.2.0",
        "pbr==5.11.1",
        "Pygments==2.14.0",
        "PyYAML==6.0",
        "rich==13.3.2",
        "smmap==5.0.0",
        "stevedore==5.0.0",
    ],
)
