name: Ollivander shop

on: 
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_ATLAS_URI: '${{ secrets.MONGO_ATLAS_URI }}'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python v${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          export MONGO_ATLAS_URI=${{ secrets.MONGO_ATLAS_URI }}
          echo $MONGO_ATLAS_URI
          pip install black pytest
          pip install -r requirements.txt
      - name: Black formatting
        run: |
          black .
      - name: Test with pytest and coverage
        run: |
          coverage run -m pytest
      - name: Coverage report
        run:
          coverage report
