name: Ollivander shop

on: 
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_ATLAS_URI: "${{ secrets.MONGO_ATLAS_URI }}"
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python v${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          export MONGO_ATLAS_URI="${{ secrets.MONGO_ATLAS_URI }}"
          echo $MONGO_ATLAS_URI
      - name: Black formatting
        run: |
          black .
      - name: Test with pytest and coverage
        run: |
          coverage run -m pytest
      - name: Coverage report
        run:
          coverage report
