name: Ollivander shop

on: 
  # Select the branch in which this will occurr
  push:
    branches:
      - main
      - develop

jobs:
  # What is going to happen
  build:
    # Setting up a container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    # Steps to follow at the workflow
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python v${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Black formatting
        run: |
          black .
      - name: Test with pytest and coverage
        with:
          super_secret: ${{secrest.MONGO_ATLAS_URI}}
        run: |
          coverage run -m pytest
      - name: Coverage report
        run:
          coverage report
      # When Env Variables are created in /settings/secrets/actions you can call it as ${{secrets.[name of the var]}}
