name: Ollivander Shop

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build

      - name: Run tests
        run: |
          docker-compose exec -T api-development pytest --cov="ollivanders-app" --cov-fail-under=90

      - name: Run code formatting check
        run: |
          docker-compose exec -T api-development black --check .

      - name: Coverage report
        run: |
          docker-compose exec -T api-development coverage report

      - name: Shut down Docker Compose
        run: |
          docker-compose down
